/**
 * src/db/schema.js
 * Tạo bảng nếu chưa tồn tại — chạy 1 lần khi setup hoặc khi server khởi động
 */
const { pool } = require("./pool");

const SCHEMA_SQL = `
-- ── Tài khoản người dùng ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tbl_accounts (
  id            VARCHAR(50)  NOT NULL,
  fullName      VARCHAR(100) NOT NULL,
  phone         VARCHAR(15)  NOT NULL,
  email         VARCHAR(100) NOT NULL,
  password      VARCHAR(255) NOT NULL COMMENT 'Lưu dạng bcrypt hash',
  birthDate     DATE         DEFAULT NULL,
  gender        ENUM('MALE','FEMALE') DEFAULT 'MALE',
  hometown      VARCHAR(255) DEFAULT NULL,
  address       VARCHAR(255) DEFAULT NULL,
  notes         TEXT         DEFAULT NULL,
  role          ENUM('ADMIN','LEADER','TREASURER','MEMBER','GUEST') NOT NULL DEFAULT 'GUEST',
  status        ENUM('ACTIVE','PENDING_ADMIN','PENDING_LEADER','BLOCKED','REJECTED','PENDING_DELETE') NOT NULL DEFAULT 'PENDING_ADMIN',
  inviteCode    VARCHAR(50)  NOT NULL,
  mappedMemberId VARCHAR(50) DEFAULT NULL COMMENT 'Liên kết node gia phả',
  rejectionReason TEXT       DEFAULT NULL,
  blockReason   TEXT         DEFAULT NULL,
  registeredAt  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_phone (phone),
  UNIQUE KEY uq_email (email),
  KEY idx_status (status),
  KEY idx_role   (role)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Thành viên gia phả ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tbl_members (
  id               VARCHAR(50)  NOT NULL,
  fullName         VARCHAR(100) NOT NULL,
  gender           ENUM('MALE','FEMALE') NOT NULL,
  livingStatus     ENUM('ALIVE','DECEASED') NOT NULL DEFAULT 'ALIVE',
  birthDate        DATE         DEFAULT NULL,
  birthDateLunar   VARCHAR(50)  DEFAULT NULL,
  deathDate        DATE         DEFAULT NULL,
  deathDateLunar   VARCHAR(50)  DEFAULT NULL,
  phone            VARCHAR(15)  DEFAULT NULL,
  email            VARCHAR(100) DEFAULT NULL,
  currentAddress   VARCHAR(255) DEFAULT NULL,
  originAddress    VARCHAR(255) DEFAULT NULL,
  generation       INT          NOT NULL DEFAULT 1,
  fatherId         VARCHAR(50)  DEFAULT NULL,
  motherId         VARCHAR(50)  DEFAULT NULL,
  spouseId         VARCHAR(50)  DEFAULT NULL,
  job              VARCHAR(100) DEFAULT NULL,
  representativeRole VARCHAR(100) DEFAULT NULL,
  notes            TEXT         DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_generation (generation),
  KEY idx_father     (fatherId),
  KEY idx_spouse     (spouseId),
  CONSTRAINT fk_member_father FOREIGN KEY (fatherId) REFERENCES tbl_members(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_member_spouse FOREIGN KEY (spouseId) REFERENCES tbl_members(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Sự kiện dòng họ ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tbl_events (
  id               VARCHAR(50)  NOT NULL,
  title            VARCHAR(150) NOT NULL,
  type             ENUM('DEATH_ANNIVERSARY','MEETING','GRAVE_VISIT','OTHER') NOT NULL DEFAULT 'OTHER',
  startDate        DATE         NOT NULL,
  startTime        VARCHAR(5)   DEFAULT NULL COMMENT 'HH:MM',
  endDate          DATE         DEFAULT NULL,
  lunarDateLabel   VARCHAR(100) DEFAULT NULL,
  location         VARCHAR(255) NOT NULL,
  description      TEXT         DEFAULT NULL,
  status           ENUM('UPCOMING','COMPLETED','POSTPONED','CANCELLED') NOT NULL DEFAULT 'UPCOMING',
  isAutoGenerated  TINYINT(1)   DEFAULT 0,
  deceasedMemberId VARCHAR(50)  DEFAULT NULL,
  cancelReason     TEXT         DEFAULT NULL,
  postponeReason   TEXT         DEFAULT NULL,
  createdBy        VARCHAR(100) DEFAULT NULL,
  createdAt        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_startDate (startDate),
  KEY idx_status    (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── RSVP sự kiện ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tbl_event_rsvps (
  id              INT          AUTO_INCREMENT NOT NULL,
  eventId         VARCHAR(50)  NOT NULL,
  accountId       VARCHAR(50)  NOT NULL,
  fullName        VARCHAR(100) NOT NULL,
  status          ENUM('ATTENDING','ABSENT','UNDECIDED') NOT NULL DEFAULT 'UNDECIDED',
  additionalGuests INT         NOT NULL DEFAULT 0,
  reason          TEXT         DEFAULT NULL,
  updatedAt       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_event_account (eventId, accountId),
  CONSTRAINT fk_rsvp_event FOREIGN KEY (eventId) REFERENCES tbl_events(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Giao dịch quỹ ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tbl_transactions (
  id              VARCHAR(50)  NOT NULL,
  type            ENUM('INCOME','EXPENSE') NOT NULL,
  category        ENUM('ANNUAL_FEE','VOLUNTARY','SPONSORSHIP','EVENT_ORGANIZATION','TEMPLE_REPAIR','CHARITY_STUDY','OTHER') NOT NULL DEFAULT 'OTHER',
  amount          BIGINT       NOT NULL COMMENT 'VNĐ',
  date            DATE         NOT NULL,
  payerOrReceiver VARCHAR(150) NOT NULL,
  memberId        VARCHAR(50)  DEFAULT NULL,
  description     VARCHAR(255) NOT NULL,
  recordedBy      VARCHAR(100) DEFAULT NULL,
  createdAt       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_date (date),
  KEY idx_type (type),
  CONSTRAINT fk_tx_member FOREIGN KEY (memberId) REFERENCES tbl_members(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Định mức niên liễm ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tbl_annual_quota (
  year             INT          NOT NULL,
  amountPerMember  BIGINT       NOT NULL DEFAULT 200000,
  description      VARCHAR(255) DEFAULT NULL,
  updatedAt        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (year)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Nhật ký kiểm toán ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tbl_audit_logs (
  id         INT          AUTO_INCREMENT NOT NULL,
  timestamp  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actorName  VARCHAR(100) NOT NULL,
  action     VARCHAR(100) NOT NULL,
  module     VARCHAR(100) NOT NULL,
  details    TEXT         NOT NULL,
  PRIMARY KEY (id),
  KEY idx_timestamp (timestamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
`;

async function runSchema() {
  const conn = await pool.getConnection();
  try {
    // Tách từng statement và chạy tuần tự
    const statements = SCHEMA_SQL
      .split(";")
      .map(s => s.trim())
      .filter(s => s.length > 0 && !s.startsWith("--"));

    for (const sql of statements) {
      await conn.query(sql);
    }
    console.log("✅ Schema created/verified");
  } finally {
    conn.release();
  }
}

module.exports = { runSchema };
// Bảng mã mời động
const CREATE_INVITE_CODES = `
CREATE TABLE IF NOT EXISTS tbl_invite_codes (
  code        VARCHAR(50)  NOT NULL,
  createdBy   VARCHAR(100) NOT NULL COMMENT 'fullName của Trưởng họ tạo',
  createdAt   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expiresAt   DATETIME     DEFAULT NULL COMMENT 'NULL = không hết hạn',
  usageLimit  INT          DEFAULT NULL COMMENT 'NULL = không giới hạn lượt',
  usedCount   INT          NOT NULL DEFAULT 0,
  note        VARCHAR(255) DEFAULT NULL COMMENT 'Ghi chú mục đích',
  isActive    TINYINT(1)   NOT NULL DEFAULT 1,
  PRIMARY KEY (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`;

pool.query(CREATE_INVITE_CODES).catch(e => console.error('Schema invite_codes:', e.message));