import React, { useState } from "react";
import { useApp, CLAN_PROFILE } from "../context/AppContext";
import { UserRole, EventType, EventStatus, LivingStatus } from "../types";
import GiaPhaTree from "./GiaPhaPage";
import MemberDataTable from "./MemberPage";
import CalendarMonth from "./EventsPage";
import FinanceFund from "./FinancePage";
import AccountManager from "./AccountsPage";
import ClanProfileView from "./ProfilePage";

export function GiaPhaPageWrapper() {
  const { members, accounts, currentAccount, addMember, updateMember, deleteMember, approveByLeader } = useApp();
  return (
    <GiaPhaTree members={members} currentAccount={currentAccount} allAccounts={accounts}
      onAddMember={(m: any) => addMember(m)} onUpdateMember={updateMember}
      onDeleteMember={(id: string) => deleteMember(id)}
      onLinkAccountToNode={(accountId: string, memberId: string) =>
        approveByLeader(accountId, UserRole.MEMBER, memberId)} />
  );
}

export function MemberPageWrapper() {
  const { members, currentAccount, updateMember, deleteMember } = useApp();
  return (
    <MemberDataTable members={members} currentAccount={currentAccount}
      onEditMember={updateMember} onDeleteMember={(id: string) => deleteMember(id)} />
  );
}

export function EventsPageWrapper() {
  const { events, members, currentAccount, addEvent, updateEvent } = useApp();
  const handleAutoGioc = () => {
    members.filter(m => m.livingStatus === LivingStatus.DECEASED && m.deathDateLunar).forEach(m => {
      const exists = events.some(e => e.type === EventType.DEATH_ANNIVERSARY && e.deceasedMemberId === m.id);
      if (!exists) {
        const [d, mo] = (m.deathDateLunar || "1/1").split("/").map(Number);
        const year = new Date().getFullYear();
        const dateStr = new Date(year, mo - 1, d).toISOString().split("T")[0];
        addEvent({ title: `Lễ Giỗ: ${m.fullName}`, type: EventType.DEATH_ANNIVERSARY,
          startDate: dateStr, startTime: "09:00", lunarDateLabel: `${m.deathDateLunar} Âm`,
          location: "Từ đường dòng họ", description: `Giỗ cố ${m.fullName}.`,
          status: EventStatus.UPCOMING, isAutoGeneratedAnniversary: true,
          deceasedMemberId: m.id, createdBy: "Hệ thống" });
      }
    });
  };
  return (
    <CalendarMonth events={events} members={members} currentAccount={currentAccount}
      onAddEvent={(e: any) => addEvent(e)} onUpdateEvent={updateEvent}
      onAutoGenerateGiocles={handleAutoGioc} />
  );
}

export function FinancePageWrapper() {
  const { transactions, annualQuota, currentAccount, members, addTransaction, updateQuota } = useApp();
  return (
    <FinanceFund transactions={transactions} annualQuota={annualQuota} currentAccount={currentAccount}
      allMembers={members} onAddTransaction={(t: any) => addTransaction(t)} onUpdateQuota={updateQuota} />
  );
}

export function AccountsPageWrapper() {
  const {
    accounts, members, currentAccount, auditLogs, register,
    approveByAdmin, approveByLeader, rejectAccount,
    blockAccount, unblockAccount, refreshAccounts,
    requestDeleteAccount, approveDeleteAccount, rejectDeleteAccount, editAccount,
  } = useApp();

  return (
    <AccountManager
      accounts={accounts}
      members={members}
      currentAccount={currentAccount}
      auditLogs={auditLogs}
      onApproveByAdmin={approveByAdmin}
      onRejectByAdmin={rejectAccount}
      onToggleBlockAccount={(id, isBlocking, reason) =>
        isBlocking ? blockAccount(id, reason || "") : unblockAccount(id)
      }
      onAddGuestAccount={(g: any) =>
        register({
          fullName: g.fullName, phone: g.phone, email: g.email || "",
          password: g.password || "Dongho@123",
          confirmPassword: g.password || "Dongho@123",
          birthDate: g.birthDate || "", gender: g.gender || "MALE",
          hometown: g.hometown || "", address: g.address || "",
          notes: g.notes || "", inviteCode: g.inviteCode || "SYSTEM_ROOT",
        })
      }
      onApproveByLeader={approveByLeader}
      onRequestDeleteAccount={requestDeleteAccount}
      onApproveDeleteAccount={approveDeleteAccount}
      onRejectDeleteAccount={rejectDeleteAccount}
      onEditAccount={editAccount}
      refreshAccounts={refreshAccounts}
      onAddAuditLog={() => {}}
    />
  );
}

export function ProfilePageWrapper() {
  const { currentAccount } = useApp();
  const [profile, setProfile] = useState(CLAN_PROFILE);
  return (
    <ClanProfileView clanProfile={profile} currentAccount={currentAccount} onUpdateProfile={setProfile} />
  );
}