import React, { useState, useEffect } from "react";
import { useApp, CLAN_PROFILE } from "../context/AppContext";
import { UserRole, EventType, EventStatus, LivingStatus } from "../types";
import GiaPhaTree from "./GiaPhaPage";
import MemberDataTable from "./MemberPage";
import CalendarMonth from "./EventsPage";
import FinanceFund from "./FinancePage";
import AccountManager from "./AccountsPage";
import ClanProfileView from "./ProfilePage";
import ClanInfoPage from "./ClanInfoPage";

export function GiaPhaPageWrapper() {
  const { members, accounts, currentAccount, addMember, updateMember, deleteMember, approveByLeader, unlinkAccountFromNode } = useApp();
  return (
    <GiaPhaTree members={members} currentAccount={currentAccount} allAccounts={accounts}
      onAddMember={(m: any) => addMember(m)} onUpdateMember={updateMember}
      onDeleteMember={(id: string, reason: string, notes?: string) => deleteMember(id, reason, notes)}
      onLinkAccountToNode={(accountId: string, memberId: string) =>
        approveByLeader(accountId, UserRole.MEMBER, memberId)}
      onUnlinkAccount={(accountId: string) => unlinkAccountFromNode(accountId)} />
  );
}

export function MemberPageWrapper() {
  const { members, currentAccount, updateMember, deleteMember } = useApp();
  return (
    <MemberDataTable members={members} currentAccount={currentAccount}
      onEditMember={updateMember}
      onDeleteMember={(id: string, reason: string, notes?: string) => deleteMember(id, reason, notes)} />
  );
}

export function EventsPageWrapper() {
  const { events, members, accounts, currentAccount, addEvent, updateEvent, refreshEvents, submitRsvp } = useApp();

  // Dữ liệu sự kiện/RSVP trước đây chỉ tải 1 lần lúc đăng nhập, nên nếu một tài khoản khác
  // (ví dụ thành viên) RSVP hoặc Trưởng họ hủy/hoãn sự kiện ở phiên đăng nhập khác, phiên
  // đang mở sẵn mục "Sự kiện" sẽ không tự thấy thay đổi đó. Tự tải lại mỗi khi vào tab này
  // + định kỳ vài giây/lần để dữ liệu luôn gần như thời gian thực.
  useEffect(() => {
    refreshEvents();
    const interval = setInterval(() => { refreshEvents(); }, 12000);
    return () => clearInterval(interval);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleAutoGioc = () => {
    members.filter(m => m.livingStatus === LivingStatus.DECEASED && m.deathDateLunar).forEach(m => {
      const exists = events.some(e => e.type === EventType.DEATH_ANNIVERSARY && e.deceasedMemberId === m.id);
      if (!exists) {
        const [d, mo] = (m.deathDateLunar || "1/1").split("/").map(Number);
        const year = new Date().getFullYear();
        const dateStr = new Date(year, mo - 1, d).toISOString().split("T")[0];
        addEvent({ title: `Lễ Giỗ: ${m.fullName}`, type: EventType.DEATH_ANNIVERSARY,
          startDate: dateStr, startTime: "09:00", lunarDateLabel: `${m.deathDateLunar} Âm`,
          location: "Từ đường dòng họ", description: `Giỗ cố ${m.fullName}.`,
          status: EventStatus.UPCOMING, isAutoGeneratedAnniversary: true,
          deceasedMemberId: m.id, createdBy: "Hệ thống" });
      }
    });
  };
  return (
    <CalendarMonth events={events} members={members} accounts={accounts} currentAccount={currentAccount}
      onAddEvent={(e: any) => addEvent(e)} onUpdateEvent={updateEvent}
      onAutoGenerateGiocles={handleAutoGioc} onRefresh={refreshEvents}
      onSubmitRsvp={submitRsvp} />
  );
}

export function FinancePageWrapper() {
  const { transactions, annualQuota, currentAccount, members, addTransaction, updateQuota } = useApp();
  return (
    <FinanceFund transactions={transactions} annualQuota={annualQuota} currentAccount={currentAccount}
      allMembers={members as any} onAddTransaction={(t: any) => addTransaction(t)} onUpdateQuota={updateQuota} />
  );
}

export function AccountsPageWrapper() {
  const {
    accounts, members, currentAccount, auditLogs, register,
    approveByAdmin, approveByLeader, rejectAccount,
    blockAccount, unblockAccount, refreshAccounts,
    requestDeleteAccount, approveDeleteAccount, rejectDeleteAccount, editAccount,
  } = useApp();

  return (
    <AccountManager
      accounts={accounts}
      members={members}
      currentAccount={currentAccount}
      auditLogs={auditLogs}
      onApproveByAdmin={approveByAdmin}
      onRejectByAdmin={rejectAccount}
      onToggleBlockAccount={(id, isBlocking, reason) =>
        isBlocking ? blockAccount(id, reason || "") : unblockAccount(id)
      }
      onAddGuestAccount={(g: any) =>
        register({
          fullName: g.fullName, phone: g.phone, email: g.email || "",
          password: g.password || "Dongho@123",
          confirmPassword: g.password || "Dongho@123",
          birthDate: g.birthDate || "", gender: g.gender || "MALE",
          hometown: g.hometown || "", address: g.address || "",
          notes: g.notes || "", inviteCode: g.inviteCode || "SYSTEM_ROOT",
        })
      }
      onApproveByLeader={approveByLeader}
      onRequestDeleteAccount={requestDeleteAccount}
      onApproveDeleteAccount={approveDeleteAccount}
      onRejectDeleteAccount={rejectDeleteAccount}
      onEditAccount={editAccount}
      refreshAccounts={refreshAccounts}
      onAddAuditLog={() => {}}
    />
  );
}

export function ProfilePageWrapper() {
  const { currentAccount } = useApp();
  return <ClanProfileView currentAccount={currentAccount} />;
}

export function ClanInfoPageWrapper() {
  const { currentAccount } = useApp();
  return <ClanInfoPage currentAccount={currentAccount} />;
}