/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export enum Gender {
  MALE = "MALE",
  FEMALE = "FEMALE"
}

export enum LivingStatus {
  ALIVE = "ALIVE",
  DECEASED = "DECEASED"
}

export enum UserRole {
  ADMIN = "ADMIN", // Quản trị viên hệ thống
  LEADER = "LEADER", // Trưởng họ / Hội đồng gia tộc
  TREASURER = "TREASURER", // Ban tài chính / Thủ quỹ
  MEMBER = "MEMBER", // Thành viên dòng họ
  GUEST = "GUEST" // Khách chưa duyệt hoặc đang chờ map
}

export enum AccountStatus {
  PENDING_ADMIN = "PENDING_ADMIN",
  PENDING_LEADER = "PENDING_LEADER",
  ACTIVE = "ACTIVE",
  BLOCKED = "BLOCKED",
  REJECTED = "REJECTED",
  PENDING_DELETE = "PENDING_DELETE"
}

export interface UserAccount {
  id: string;
  phone: string;
  email: string;
  fullName: string;
  password?: string; // Mật khẩu bảo mật tài khoản
  birthDate?: string; // Ngày sinh
  gender?: Gender;     // Giới tính
  hometown?: string;  // Quê quán
  address?: string;   // Địa chỉ cư trú hiện thời
  notes?: string;     // Ghi chú / Lời khai nhân thân
  role: UserRole;
  status: AccountStatus;
  inviteCode: string;
  registeredAt: string;
  mappedMemberId?: string; // ID của nút thành viên trong Cây gia phả
  rejectionReason?: string;
  blockReason?: string;
  clanId?: string;     // Dòng họ mà tài khoản thuộc về
  clanName?: string;   // Tên dòng họ (lấy từ tbl_clan_info, dùng để Admin nhóm hiển thị)
}

export interface ClanMember {
  id: string;
  fullName: string;
  gender: Gender;
  livingStatus: LivingStatus;
  birthDate: string; // Dương lịch YYYY-MM-DD
  deathDate?: string; // Dương lịch YYYY-MM-DD
  birthDateLunar?: string; // Ghi chú ngày sinh âm lịch (ví dụ: 15/08)
  deathDateLunar?: string; // Hàng năm giỗ chạp tính theo âm lịch này (ví dụ: 12/03)
  phone?: string;
  email?: string;
  currentAddress?: string;
  originAddress?: string; // Quê quán
  generation: number; // Đời thứ mấy (1: Cụ tổ, 2: Con cụ tổ...)
  fatherId?: string;
  motherId?: string;
  spouseId?: string; // ID vợ/chồng liên kết đặc biệt
  notes?: string;
  job?: string; // Nghề nghiệp / Chức danh hiện tại
  representativeRole?: string; // Chức vụ trong dòng họ (Trưởng tộc, Trưởng chi 1, Thư ký...)
}

export enum EventType {
  DEATH_ANNIVERSARY = "DEATH_ANNIVERSARY", // Giỗ chạp (Tâm linh)
  MEETING = "MEETING",                  // Họp mục dòng họ / Đại hội
  GRAVE_VISIT = "GRAVE_VISIT",          // Tảo mộ / Lễ thanh minh
  OTHER = "OTHER"
}

export enum EventStatus {
  UPCOMING = "UPCOMING",     // Sắp diễn ra
  COMPLETED = "COMPLETED",   // Đã diễn ra
  POSTPONED = "POSTPONED",   // Tạm hoãn
  CANCELLED = "CANCELLED"    // Đã hủy
}

export enum RSVPStatus {
  ATTENDING = "ATTENDING",
  ABSENT = "ABSENT",
  UNDECIDED = "UNDECIDED"
}

export interface EventRSVP {
  accountId: string;
  fullName: string;
  status: RSVPStatus;
  additionalGuests: number;
  reason?: string; // Bắt buộc khi vắng mặt
  updatedAt: string;
}

export interface ClanEvent {
  id: string;
  title: string;
  type: EventType;
  startDate: string; // Dương lịch YYYY-MM-DD
  startTime?: string; // HH:MM
  endDate?: string;
  endTime?: string; // HH:MM
  attendeeType?: "ALL" | "ROLE" | "CUSTOM"; // Thành phần tham dự
  attendeeRoles?: string[];
  attendeeIds?: string[];
  lunarDateLabel?: string; // Ngày Âm lịch tương ứng (ví dụ: 10/03 Âm lịch)
  location: string;
  description: string;
  status: EventStatus;
  isAutoGeneratedAnniversary?: boolean; // Tự động tạo từ danh sách người đã khuất
  deceasedMemberId?: string;           // Liên kết tới người đã mất nếu là giỗ chạp
  createdBy: string; // Tên người tạo
  createdAt: string;
  rsvps: EventRSVP[];
  cancelReason?: string;
  postponeReason?: string;
  media?: string[]; // (Cũ, không còn dùng) — tư liệu sự kiện nay quản lý qua EventMedia/bảng riêng
}

// ─── Tư liệu / Hình ảnh sự kiện (lưu trữ sau sự kiện) ──────────────────────────
export enum MediaFileType {
  IMAGE = "IMAGE",
  VIDEO = "VIDEO",
  DOCUMENT = "DOCUMENT",
}

export interface EventMedia {
  id: string;
  eventId: string;
  fileName: string;       // Tên tệp đã lưu trên server
  originalName: string;   // Tên tệp gốc do người dùng tải lên
  fileUrl: string;        // Đường dẫn truy cập tệp
  fileType: MediaFileType;
  mimeType?: string;
  fileSize: number;       // Bytes
  uploadedBy?: string;
  uploadedAt: string;
}


export enum TransactionType {
  INCOME = "INCOME",    // Thu
  EXPENSE = "EXPENSE"   // Chi
}

export enum FundCategory {
  ANNUAL_FEE = "ANNUAL_FEE",       // Đóng đóng niên liễm định mức
  VOLUNTARY = "VOLUNTARY",         // Đóng góp tự nguyện / Phát tâm
  SPONSORSHIP = "SPONSORSHIP",     // Tài trợ lớn
  EVENT_ORGANIZATION = "EVENT_ORGANIZATION", // Chi tổ chức sự kiện / Cúng lễ
  TEMPLE_REPAIR = "TEMPLE_REPAIR", // Chi xây dựng / Sửa sang từ đường
  CHARITY_STUDY = "CHARITY_STUDY", // Chi khuyến học / Mừng thọ / Hiếu hỷ
  OTHER = "OTHER"
}

export interface FundTransaction {
  id: string;
  type: TransactionType;
  category: FundCategory;
  amount: number;
  date: string; // YYYY-MM-DD
  payerOrReceiver: string; // Người đóng hoặc nhận tiền
  memberId?: string; // Liên kết tới thành viên đóng tiền (nếu có)
  description: string;
  recordedBy: string; // Ban tài chính ghi nhận
  createdAt: string;
}

export interface AnnualQuota {
  year: number;
  amountPerMember: number; // Định mức đóng hằng năm của mỗi đinh/thành viên
  description: string;
  notes?: string;
  updatedAt?: string;
  clanId?: string;
}

export interface AuditLog {
  id: string;
  timestamp: string;
  actorName: string;
  action: string;
  module: string;
  details: string;
}